version: "3.8"

services:
  redis:
    image: redis:7.0.2-alpine3.16

  web:
    build:
      context: backend
      dockerfile: Dockerfile
    command: gunicorn Backend.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      - redis

  celery-worker:
    build:
      context: backend
      dockerfile: Dockerfile
    command: celery -A Backend worker -B -l info
    stop_grace_period: 30s
    env_file:
      - .env
    depends_on:
      - redis

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.nginx
    ports:
      - 8000:80
    depends_on:
      - web

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 10203:80
      - 443:443
    volumes:
      - ./config.js:/usr/share/nginx/html/config.js
      - ./ssl.crt:/usr/nginx/ssl.crt
      - ./ssl.key:/usr/nginx/ssl.key
    depends_on:
      - backend
