version: "3.8"

services:
  redis:
    image: redis:7.0.2-alpine3.16

  web:
    logging:
      driver: gcplogs
      options:
        labels:
          - MKT-UAT-WEB
    image: asia-southeast1-docker.pkg.dev/merkle-trading-terminal-359611/main/mkt-backend:v0.0.2-dev.0
    command: gunicorn Backend.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      - redis

  celery-beat:
    logging:
      driver: gcplogs
      options:
        labels:
          - MKT-UAT-CELERY-BEAT
    image: asia-southeast1-docker.pkg.dev/merkle-trading-terminal-359611/main/mkt-backend:v0.0.2-dev.0
    command: celery -A Backend beat
    stop_grace_period: 30s
    env_file:
      - .env
    depends_on:
      - redis

  celery-worker:
    logging:
      driver: gcplogs
      options:
        labels:
          - MKT-UAT-CELERY-WORKER
    image: asia-southeast1-docker.pkg.dev/merkle-trading-terminal-359611/main/mkt-backend:v0.0.2-dev.0
    command: celery -A Backend worker -l info
    stop_grace_period: 30s
    env_file:
      - .env
    depends_on:
      - redis

  backend:
    logging:
      driver: gcplogs
      options:
        labels:
          - MKT-UAT-BACKEND
    image: asia-southeast1-docker.pkg.dev/merkle-trading-terminal-359611/main/mkt-nginx:v0.0.2-dev.0
    ports:
      - 8000:80
    depends_on:
      - web

  frontend:
    logging:
      driver: gcplogs
      options:
        labels:
          - MKT-UAT-FRONTEND
    image: asia-southeast1-docker.pkg.dev/merkle-trading-terminal-359611/main/mkt-frontend:v0.0.2-dev.0
    ports:
      - 80:80
    volumes:
      - ./config.js:/usr/share/nginx/html/config.js
    depends_on:
      - backend
