version: "3.8"

services:

  pgsql:
    build: ./pgsql
    env_file:
      - .env

  web:
    build:
      context: ./backend
    command: gunicorn Backend.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      - redis
      - pgsql

  celery-beat:
    build:
      context: ./backend
    command: celery -A Backend beat
    stop_grace_period: 30s
    env_file:
      - .env
    depends_on:
      - redis
      - pgsql

  celery-worker:
    build:
      context: ./backend
    command: celery -A Backend worker -l info
    stop_grace_period: 30s
    env_file:
      - .env
    depends_on:
      - redis
      - pgsql

  redis:
    image: redis:7.0.2-alpine3.16

  nginx:
    build:
      context: ./backend
      dockerfile: Dockerfile.nginx
    ports:
      - 8000:80
    depends_on:
      - web

  frontend:
    build:
      context: ./frontend
    ports:
      - 80:80
    env_file:
      - .env
